### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by DenisMPar** [alexbalieiro/lostpets-fe#2]
Hola Alex, te felicito por el desafío.
La página anda muy bien solo que el botón de subir la imagen de la mascota se queda cargando y nunca me abre la ventana para subir la imagen. 
![Screenshot_14](https://user-images.githubusercontent.com/80976314/186545824-10dbe83e-cf79-49a5-9b0e-323dabe90bf4.png)
Si arrastro la imagen el dropbox funciona de 10.
![Screenshot_15](https://user-images.githubusercontent.com/80976314/186545903-693f71c5-c5f0-4753-b1e3-516e3558661f.png)
Arreglate eso y estaríamos.
Despues te dejo algunos detalles:
Si edito una mascota, la pagina de edit después me envía a mis mascotas y el cambio en el nombre se ve reflejado pero en la ubicacion no, tengo que recargar la página para que se vea.

![Screenshot_19](https://user-images.githubusercontent.com/80976314/186546697-a0c621d5-a068-486a-b36b-b1dc8e7a0759.png)
![Screenshot_20](https://user-images.githubusercontent.com/80976314/186546708-47359baf-8333-4578-8e38-f8ca497f8f31.png)

La idea de arrastrar el marcador esta buena pero quizás le agregaría un form que me lleve mas o menos a la dirección para no tener que andar alejando el mapa y buscando mi ubicación "a mano".

Por lo demas la página anda muy bien y esta muy linda. Dejame un comentario cuando arregles eso del botón y te lo apruebo.

**Comment by alexbalieiro** [comment]
Hola Denis, muchas gracias por la devolución, ya corregí lo de la carga de fotos de las mascotas, me había hecho renegar antes porque en algunos navegadores lo tomaba y en otros no, pero ahí hice la prueba y debería funcionar, también corregí la data de las mascotas, era agregar la escucha a un useEffect, me falta agregar la búsqueda en el mapa, pensé que era la forma más cómoda e intuitiva ya que como Mapbox no realiza la búsqueda por calles arrastrando el marcador me parecia que alcanzaba, pero voy a implementar una caja de texto así el usuario también tiene esa opción. Nos vemos y nuevamente gracias!

**Comment by DenisMPar** [comment]
Impecable Alex quedo andando de 10.
Si lo del marcador esta buenísimo porque es mucho mas preciso, por eso decía que un form para que me lleve mas o menos a la ubicación y después mover el marcador quedaría increíble.
Nos vemos en el próximo modulo. Aprobado!

**Comment by alexbalieiro** [comment]
Si, tenes razón, lo voy a implementar, gracias Denis, nos vemos
